default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: board_game_borrowing
  password: your_password

development:
  <<: *default
  database: board_game_borrowing_development

test:
  <<: *default
  database: board_game_borrowing_test

production:
  <<: *default
  database: board_game_borrowing_production
  username: board_game_borrowing
  password: your_password
