name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libxml2-dev libxslt1-dev zlib1g-dev

      - name: Cache Bundler dependencies
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: bundler-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundler-${{ runner.os }}-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: false  # Désactiver le cache automatique

      - name: Ensure correct Ruby platform
        run: bundle lock --add-platform x86_64-linux

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3 --no-cache

      - name: Scan for vulnerabilities
        run: bin/brakeman --no-pager

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable curl \
            libjemalloc2 libvips postgresql-client \
            build-essential libxml2-dev libxslt1-dev zlib1g-dev

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: false

      - name: Ensure correct Ruby platform
        run: bundle lock --add-platform x86_64-linux

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3 --no-cache

      - name: Setup test database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: bin/rails db:test:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bin/rails test
          bin/rails test:system

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
